### ISSUE TITLE
upgrade to ssl-config-core 0.2.1 if possible

### ISSUE THREAD

**Issue by weihsiu** [eed3si9n/gigahorse#10]
i am using the latest akka 2.4.10 which pulls in ssl-config-core 0.2.1.  when i use Gigahorse, it throws me this exception which i believe is due to an use of older ssl-config-core:

java.lang.NoSuchMethodError: com.typesafe.sslconfig.ssl.SSLConfigFactory$.defaultConfig()Lcom/typesafe/sslconfig/ssl/SSLConfig;
        at gigahorse.ConfigDefaults$.<init>(ConfigExtra.scala:105)
        at gigahorse.ConfigDefaults$.<clinit>(ConfigExtra.scala)
        at gigahorse.Config$.apply(Config.scala:126)
        at gigahorse.Gigahorse.config(Gigahorse.scala:49)
        at gigahorse.Gigahorse.withHttp(Gigahorse.scala:41)
...

**Comment by eed3si9n** [comment]
I intentionally picked rather older stack for Gigahorse 0.1.x so I could potentially use it from JDK 6. I should start working on the design for Gigahorse 0.2.x with JDK 8 stack.

**Comment by eed3si9n** [comment]
Fixed in #12 by @alexdupre
